using System;
using System.Collections.Generic;
using burgershack.Models;

namespace burgershack.Services
{
    class BurgershackService
    {
        private Shack Shack { get; set; } = new Shack(); //object to hold data
        ///<summary> collection of messages generated by the service to be drawn to the console by the controller</summary>
        public List<string> Messages = new List<string>();


        public void PrintMenu()
        {
            Messages.Add("----Menu----");
            int index = 1;
            foreach (var item in Shack.Menu)
            {
                Messages.Add(index.ToString() + ") " + item.GetMenuLineItem());
                index++;
            }
            Messages.Add("press (o) to order or (n) to add a new item or (q) to quit");
        }

        public void MakeBurger(string name, string[] ingredients, float price, int kCals)
        {
            Burger newBurger = new Burger(name, ingredients, price, kCals);
            Shack.Menu.Add(newBurger);
            Messages.Add($"Successfully made {name}");
            PrintMenu();
        }
    }
}